# SonarCloud configuration
sonar.projectKey=misw-4102-procesosdedesarrolloagil
sonar.projectName=MISW4203 Vinilos App
sonar.projectVersion=1.0
sonar.organization=misw-4102-procesosdedesarrolloagil
sonar.host.url=https://sonarcloud.io

# Source code
sonar.sources=.
sonar.inclusions=**/src/main/**,**/src/main/kotlin/**,**/src/main/java/**
sonar.exclusions=**/src/test/**,**/src/androidTest/**,**/build/**,**/.gradle/**
sonar.tests=**/src/test/**,**/src/androidTest/**

# Binary files
sonar.java.binaries=**/build/intermediates/classes/**,**/build/tmp/kotlin-classes/**

# Opcional: agrega reportes cuando los tengas (JaCoCo, lint, etc.)

